### ISSUE TITLE
Trying multiple fires within a trigger and adding a timer value - Not an issue, more like a syntax question or limitation

### ISSUE THREAD

**Issue by Milkshake665** [eouia/MMM-NotificationTrigger#10]
Hi,
Awesome module! I am struggling with the syntax for multiple fires within a single trigger. I finally came to a syntax that does not break my config, but it does not display the alert for some reason:
```js
{
      module: "MMM-NotificationTrigger",
      config: {
        triggers:[
          {
            trigger: "PLAY_SOUND",
            fires: [
              {
                fire:"USER_PRESENCE",
                payload: function(payload) {
                  return false
                }
              },

              {
                fire:"SHOW_ALERT",
                payload: function(payload) {
                  return {
                    type: "notification",
                    title: "Porten",
                    message: "Der er nogen ved porten!"
                    }
                },
              }
            ],
          },
        ]
      }
},
```

Furthermore, is there any way to add the timer value to SHOW_ALERT and what format should that be in?

timer: 1000,     ?

Best
MilkShake

**Comment by eouia** [comment]
first, you don't need to use callback function to make static payload.
```js
payload: function(payload) {
  return {
    type: "notification",
    title: "Porten",
    message: "Der er nogen ved porten!"
  }
},
```
is identically same with;
```js
payload: {
  type: "notification",
  title: "Porten",
  message: "Der er nogen ved porten!"
},
```

And in my system, both notification would be fired. Can you check frontend log?

and timer is right.

**Comment by Milkshake665** [comment]
Hi,
Ok, I struggled with that, but at one point I came to a working config with function(payload) that displayed the Alert (without a timer) and thought it was the missing callback function. However I kept changing the config syntax to a point where I could not reproduce it.

I'm not too sure how to do that. Could I use the firbug addon in Firefox for that?

**Comment by eouia** [comment]
First stop pm2 (`pm2 stop all`) Then go to MagicMirror directory, do `npm start dev`

**Comment by eouia** [comment]
Or if keyboard is connected, `Crtl+Shift+i` (Or it might vary by environment, but anyway, you can activate `developer tool` of Chrome/Chromium.)

**Comment by Milkshake665** [comment]
Hi,
From the log I can see that USER_PRESENCE is called and PLAY_SOUND, but no Alarm.

>[2020-04-03 16:29:53.763] [LOG]    [AMK2:ADDONS:SCREEN] Starts.
[2020-04-03 16:29:53.831] [LOG]    [AMK2:ADDONS:SCREEN] Response value is:  Monitor is On
[2020-04-03 16:29:53.833] [LOG]    [AMK2:ADDONS:SCREEN] Display -- Actual: true - Wanted: true
[2020-04-03 16:29:53.863] [LOG]    [2020-04-03 16:29:53] [MMM-Sounds] Quiet Time Start is: 23:59
[2020-04-03 16:29:53.864] [LOG]    [2020-04-03 16:29:53] [MMM-Sounds] Quiet Time End is: 00:00
[2020-04-03 16:29:53.876] [LOG]    [2020-04-03 16:29:53] [MMM-Sounds] Start Moment: 2020-04-03 23:59
[2020-04-03 16:29:53.884] [LOG]    [2020-04-03 16:29:53] [MMM-Sounds] End Moment: 2020-04-03 00:00
[2020-04-03 16:29:53.887] [LOG]    [2020-04-03 16:29:53] [MMM-Sounds] Playing bell.wav with 100ms delay
<

**Comment by Milkshake665** [comment]
And thank you for explaining some of the basics..!

**Comment by eouia** [comment]
Very weird. Can you change the order of `fire`?

**Comment by eouia** [comment]
> [2020-04-03 16:29:53.763] [LOG] [AMK2:ADDONS:SCREEN] Starts.
[2020-04-03 16:29:53.831] [LOG] [AMK2:ADDONS:SCREEN] Response value is: Monitor is On
[2020-04-03 16:29:53.833] [LOG] [AMK2:ADDONS:SCREEN] Display -- Actual: true - Wanted: true
[2020-04-03 16:29:53.863] [LOG] [2020-04-03 16:29:53] [MMM-Sounds] Quiet Time Start is: 23:59
[2020-04-03 16:29:53.864] [LOG] [2020-04-03 16:29:53] [MMM-Sounds] Quiet Time End is: 00:00
[2020-04-03 16:29:53.876] [LOG] [2020-04-03 16:29:53] [MMM-Sounds] Start Moment: 2020-04-03 23:59
[2020-04-03 16:29:53.884] [LOG] [2020-04-03 16:29:53] [MMM-Sounds] End Moment: 2020-04-03 00:00
[2020-04-03 16:29:53.887] [LOG] [2020-04-03 16:29:53] [MMM-Sounds] Playing bell.wav with 100ms delay


In this log I just can see MMM-Sounds work, but how do you know USER_PRESENCE notification is emitted?

**Comment by Milkshake665** [comment]
Hehe. I hate the config. Should be an easy task to swap the fires, but now the conf is broken:

Check config says line 51 Unexpsected token {

> /* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
        address: "0.0.0.0", // Address to listen on, can be:
                              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                              // - another specific IPv4/6 to listen on a specific interface
                              // - "", "0.0.0.0", "::" to listen on any interface
                              // Default, when address config is left out, is "localhost"
        port: 8080,
        ipWhitelist: [], // Set [] to allow all IP addresses
                                                               // or add a specific IPv4 of 192.168.1.5 :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

        language: "en",
        timeFormat: 24,
        units: "metric",
        // serverOnly:  true/false/"local" ,
                             // local for armv6l processors, default
                             //   starts serveronly and then starts chrome browser
                             // false, default for all  NON-armv6l devices
                             // true, force serveronly mode, because you want to.. no UI on this device

        modules: [
                        {
      module: "MMM-NotificationTrigger",
      config: {
        triggers:[
          {
            trigger: "PLAY_SOUND",
            fires: [
              {
                fire:"SHOW_ALERT",
                payload:  {

                    type: "notification",
                    title: "Porten",
                    message: "Der er nogen ved porten!"

               },

                          {
                fire:"USER_PRESENCE",
                payload: function(payload) {
                  return false
                }
               },
                          }
            ],
          },
        ]
      }
},

**Comment by eouia** [comment]
It might be a ridiculous question at this moment, but...
Which module would emit PLAY_SOUND?
In my thought, MMM-PIR will emit `USER_PRESENCE` when sensor be activated then you wants `PLAY_SOUND` and `SHOW_ALERT`.
But your configuration seems;
SOMETHING would emit `PLAY_SOUND` then `USER_PRESENCE` and `SHOW_ALERT` will be emitted. I can't understand this situation.

**Comment by Milkshake665** [comment]
Ok. So I have an automated gate. This gate (or the intercom at the gate) is able to do HTTP calls when the button is pressed. The HTTP call is minded for the MMM-Sounds module, but uses MMM-Remote-Control api:

MM_IP/remote?action=NOTIFICATION&notification=PLAY_SOUND&payload=%7B"sound"%3A"bell.wav"%2C"delay"%3A100%7D

That plays a wav file on the MM. I am using Bugsounet's AssistantMk2/Screen/PIR addon together with a PIR sensor. That fires waking up the mirror when someone pushes the button at the gate. 

Besides waking up the mirror and playing the sound, I would like the mirror to display the alert also for 10 seconds.

**Comment by eouia** [comment]
I've updated more kind log.

Anyway, for your case; I think this will work.

- MMM-NotificationTrigger also get HTTP request as a trigger.

```
http://localhost:8080/webhook?notification=DOOR_BUTTON_PRESSED
```
{
  disabled:false,
  module: "MMM-NotificationTrigger",
  config: {
    useWebhook: true,
    triggers:[
      {
        trigger: "DOOR_BUTTON_PRESSED",
        fires: [
          {
            fire: "PLAY_SOUND",
            payload: (payload) => {
              console.log("PLAY_SOUND working?")
              return {
                sound: "wobble.wav",
                delay: 1000,
              }
            }
          },
          {
            fire: "USER_PRESENCE",
            payload: (payload) => {
              console.log("USER_PRESENCE working?")
              return false
            }
          },
          {
            fire: "SHOW_ALERT",
            payload: (payload) => {
              console.log("SHOW_ALERT working?")
              return {
                type: "notification",
                title: "Porten",
                message: "Der er nogen ved porten!"
              }
            }
          },
        ]
      }
    ]
  }
},
```js

**Comment by eouia** [comment]
<img width="1644" alt="123" src="https://user-images.githubusercontent.com/1720610/78378726-b09e4b00-75d1-11ea-99a8-6b07956071bc.png">

**Comment by Milkshake665** [comment]
I updated the HTTP call to:

http://localhost:8080/webhook?notification=DOOR_BUTTON_PRESSED

and added the config.

In npm start dev I get:

[2020-04-03 17:45:34.691] [LOG]    reqget? {}

**Comment by eouia** [comment]
Update module first.

**Comment by Milkshake665** [comment]
No alarm. Worked as the other solution does. USER_PRESENCE and PLAY_SOUND is called, but no alarm is displayed.

If I do the HTTP call:

http://192.168.1.100:8080/remote?action=SHOW_ALERT&message=Der%er%nogen%ved%porten!&title=PORT&timer=10&type=alert

The alert is called properly.


> 

[2020-04-03 17:58:57.480] [LOG]    [AMK2:ADDONS:SCREEN] Hiding in 00:14:38
[2020-04-03 17:58:58.099] [LOG]    reqget? { notification: 'DOOR_BUTTON_PRESSED' }
[2020-04-03 17:58:58.166] [LOG]    [2020-04-03 17:58:58] [MMM-Sounds] Quiet Time Start is: 23:59
[2020-04-03 17:58:58.167] [LOG]    [2020-04-03 17:58:58] [MMM-Sounds] Quiet Time End is: 00:00
[2020-04-03 17:58:58.172] [LOG]    [2020-04-03 17:58:58] [MMM-Sounds] Start Moment: 2020-04-03 23:59
[2020-04-03 17:58:58.174] [LOG]    [2020-04-03 17:58:58] [MMM-Sounds] End Moment: 2020-04-03 00:00
[2020-04-03 17:58:58.178] [LOG]    [2020-04-03 17:58:58] [MMM-Sounds] Playing bell.wav with 1000ms delay
[2020-04-03 17:58:58.251] [LOG]    [AMK2:ADDONS:SCREEN] Starts.
[2020-04-03 17:58:58.354] [LOG]    [AMK2:ADDONS:SCREEN] Response value is:  Monitor is On
[2020-04-03 17:58:58.355] [LOG]    [AMK2:ADDONS:SCREEN] Display -- Actual: true - Wanted: true

**Comment by eouia** [comment]
If possible, drop out all other modules (including AMK2, MMM-Sounds and all other). Leave just MMM-NotificationTrigger and alert module. Then see the front end log. Just to check notification emitted or not.

**Comment by Milkshake665** [comment]
After uncommenting out all other modules than Alarm and
Notification-Trigger...


pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-04-03 19:46:50.796] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-03 19:46:50.806] [LOG]    Loading config ...
[2020-04-03 19:46:50.811] [LOG]    Loading module helpers ...
[2020-04-03 19:46:50.818] [LOG]    Initializing new module helper ...
[2020-04-03 19:46:50.819] [LOG]    Module helper loaded:
MMM-NotificationTrigger
[2020-04-03 19:46:50.820] [LOG]    No helper found for module: alert.
[2020-04-03 19:46:50.820] [LOG]    All module helpers loaded.
[2020-04-03 19:46:50.964] [LOG]    Starting server on port 8080 ...
[2020-04-03 19:46:50.971] [INFO]   You're using a full whitelist
configuration to allow for all IPs
[2020-04-03 19:46:50.978] [LOG]    Server started ...
[2020-04-03 19:46:50.979] [LOG]    Connecting socket for:
MMM-NotificationTrigger
[2020-04-03 19:46:50.990] [LOG]    Sockets connected & modules started ...
[2020-04-03 19:46:51.000] [LOG]    Whoops! There was an uncaught
exception...
[2020-04-03 19:46:51.001] [ERROR]  { Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1492:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:755:11)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }
[2020-04-03 19:46:51.007] [LOG]    MagicMirror will not quit, but it might
be a good idea to check why this happened. Maybe no internet connection?
[2020-04-03 19:46:51.007] [LOG]    If you think this really is an issue,
please open an issue on GitHub:
https://github.com/MichMich/MagicMirror/issues
[2020-04-03 19:46:51.162] [LOG]    Launching application.

**Comment by eouia** [comment]
That error is derived from execution multiple MM together. You might not stop pm2...

**Comment by Milkshake665** [comment]
pi@raspberrypi:~/MagicMirror/config $ pm2 stop all
[PM2] Applying action stopProcessId on app [all](ids: 0)
[PM2] [MagicMirror](0) ✓
┌─────┬────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name           │ namespace   │ version │ mode    │ pid      │
uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ MagicMirror    │ default     │ 2.11.0  │ fork    │ 0        │ 0
 │ 2    │ stopped   │ 0%       │ 0b       │ pi       │ disabled │
└─────┴────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
pi@raspberrypi:~/MagicMirror/config $ cd ..
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-04-03 19:52:34.139] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-03 19:52:34.148] [LOG]    Loading config ...
[2020-04-03 19:52:34.153] [LOG]    Loading module helpers ...
[2020-04-03 19:52:34.160] [LOG]    Initializing new module helper ...
[2020-04-03 19:52:34.160] [LOG]    Module helper loaded:
MMM-NotificationTrigger
[2020-04-03 19:52:34.161] [LOG]    No helper found for module: alert.
[2020-04-03 19:52:34.162] [LOG]    All module helpers loaded.
[2020-04-03 19:52:34.301] [LOG]    Starting server on port 8080 ...
[2020-04-03 19:52:34.307] [INFO]   You're using a full whitelist
configuration to allow for all IPs
[2020-04-03 19:52:34.314] [LOG]    Server started ...
[2020-04-03 19:52:34.315] [LOG]    Connecting socket for:
MMM-NotificationTrigger
[2020-04-03 19:52:34.326] [LOG]    Sockets connected & modules started ...
[2020-04-03 19:52:34.466] [LOG]    Launching application.

**Comment by Milkshake665** [comment]
stays at Launching applications..

**Comment by Milkshake665** [comment]
[2020-04-03 19:55:29.595] [LOG]    reqget? { notification:
'DOOR_BUTTON_PRESSED' }
[2020-04-03 19:55:31.623] [LOG]    reqget? { notification:
'DOOR_BUTTON_PRESSED' }

**Comment by Milkshake665** [comment]
Nothing else

**Comment by eouia** [comment]
See your front-end log. not backend log.
> I've updated for a more kind log. update first. you can see some more information on the front-end log.

**Comment by Milkshake665** [comment]
All modules started!
config.js:46 PLAY_SOUND working?
MMM-NotificationTrigger.js:84 [NOTTRG] PLAY_SOUND is emitted.
config.js:56 USER_PRESENCE working?
MMM-NotificationTrigger.js:84 [NOTTRG] USER_PRESENCE is emitted.
config.js:63 SHOW_ALERT working?
MMM-NotificationTrigger.js:84 [NOTTRG] SHOW_ALERT is emitted.

**Comment by eouia** [comment]
All notification is emitted as expected. Nothing wrong on the module. If there be issue, it will be another's job.

**Comment by Milkshake665** [comment]
Thank you for the help.
